# Generated by Django 4.2.10 on 2024-02-24 01:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.now)),
                ('data_devolucao_prevista', models.DateField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateField(default=django.utils.timezone.now)),
                ('status_emprestimo', models.BooleanField()),
                ('quantidade_renovacoes', models.IntegerField()),
                ('valor_multa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.TextField()),
                ('comentarios', models.TextField()),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
