# Generated by Django 4.2.10 on 2024-02-13 01:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.PositiveBigIntegerField(unique=True)),
                ('nome', models.TextField()),
                ('endereco', models.TextField()),
                ('telefone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
                ('data_registro', models.DateField(default=django.utils.timezone.now)),
                ('tipo_membro', models.TextField()),
                ('status_emprestimo', models.BooleanField()),
            ],
        ),
    ]
