# Generated by Django 4.2.10 on 2024-02-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('cpf', models.PositiveBigIntegerField(unique=True)),
                ('nome', models.TextField()),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
