# Generated by Django 4.2.10 on 2024-02-10 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c334733f-e94d-4a6d-8b45-d4bf8e8ec6ba'), editable=False, primary_key=True, serialize=False),
        ),
    ]
