# Generated by Django 4.2.10 on 2024-02-10 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1fbb65e-8374-48ca-8ce6-86b2c12bdf47'), editable=False, primary_key=True, serialize=False),
        ),
    ]
