# Generated by Django 4.2.10 on 2024-02-13 01:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('autor', models.TextField()),
                ('isbn', models.TextField(unique=True)),
                ('editora', models.TextField()),
                ('data_publicacao', models.DateField(default=django.utils.timezone.now)),
                ('genero', models.TextField()),
                ('sinopse', models.TextField()),
                ('numero_paginas', models.IntegerField()),
                ('idioma', models.TextField()),
            ],
        ),
    ]
